// Code generated by fabrica generate. DO NOT EDIT.
// Copyright © 2025 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT
//
// This file provides storage convenience functions for your resources.
// It uses the fabrica storage backend system.
//
// To modify storage behavior:
//  1. Edit pkg/codegen/templates/storage.go.tmpl
//  2. Run 'fabrica generate' to regenerate
//
// To change storage backend:
//  1. Call storage.Init() with a different backend in main.go
//  2. Options: FileBackend, EntBackend (database), or custom backend
package storage

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/openchami/fabrica/pkg/reconcile"
	fabricaStorage "github.com/openchami/fabrica/pkg/storage"

	"github.com/user/node-service/apis/example.fabrica.dev/v1"
)

// Backend is the storage backend used by all storage operations.
// Initialize this in your main.go before using any storage functions.
//
// Example:
//
//	backend, err := fabricaStorage.NewFileBackend("./data")
//	if err != nil {
//	    log.Fatal(err)
//	}
//	storage.Init(backend)
var Backend fabricaStorage.StorageBackend

// Init initializes the storage backend.
// This must be called before using any storage functions.
func Init(backend fabricaStorage.StorageBackend) {
	Backend = backend
}

// InitFileBackend is a convenience function to initialize file-based storage.
// It creates the directory if it doesn't exist.
func InitFileBackend(dataDir string) error {
	backend, err := fabricaStorage.NewFileBackend(dataDir)
	if err != nil {
		return fmt.Errorf("failed to create file backend: %w", err)
	}
	Backend = backend
	return nil
}

// ensureBackend panics if Backend is not initialized.
// This is called by all storage functions to ensure proper initialization.
func ensureBackend() {
	if Backend == nil {
		panic("storage backend not initialized: call storage.Init() or storage.InitFileBackend() in main.go")
	}
}

// Node storage operations

// LoadAllNodes retrieves all Node resources.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//
// Returns:
//   - []*v1.Node: Slice of Node resources
//   - error: Any error that occurred during loading
func LoadAllNodes(ctx context.Context) ([]*v1.Node, error) {
	ensureBackend()

	rawData, err := Backend.LoadAll(ctx, "Node")
	if err != nil {
		return nil, fmt.Errorf("failed to load all nodes: %w", err)
	}

	nodes := make([]*v1.Node, 0, len(rawData))
	for _, raw := range rawData {
		node := &v1.Node{}
		if err := json.Unmarshal(raw, node); err != nil {
			return nil, fmt.Errorf("failed to unmarshal Node: %w", err)
		}
		nodes = append(nodes, node)
	}

	return nodes, nil
}

// LoadNode retrieves a single Node resource by UID.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//   - uid: Unique identifier of the Node resource
//
// Returns:
//   - *v1.Node: The Node resource
//   - error: fabricaStorage.ErrNotFound if resource doesn't exist, other errors for failures
func LoadNode(ctx context.Context, uid string) (*v1.Node, error) {
	ensureBackend()

	rawData, err := Backend.Load(ctx, "Node", uid)
	if err != nil {
		return nil, fmt.Errorf("failed to load Node %s: %w", uid, err)
	}

	node := &v1.Node{}
	if err := json.Unmarshal(rawData, node); err != nil {
		return nil, fmt.Errorf("failed to unmarshal Node: %w", err)
	}

	return node, nil
}

// SaveNode stores a Node resource.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//   - node: The Node resource to save
//
// Returns:
//   - error: Any error that occurred during saving
func SaveNode(ctx context.Context, node *v1.Node) error {
	ensureBackend()

	data, err := json.Marshal(node)
	if err != nil {
		return fmt.Errorf("failed to marshal Node: %w", err)
	}

	if err := Backend.Save(ctx, "Node", node.Metadata.UID, data); err != nil {
		return fmt.Errorf("failed to save Node: %w", err)
	}

	return nil
}

// UpdateNode updates an existing Node resource.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//   - node: The Node resource to update
//
// Returns:
//   - error: fabricaStorage.ErrNotFound if resource doesn't exist, other errors for failures
func UpdateNode(ctx context.Context, node *v1.Node) error {
	ensureBackend()

	// Check if resource exists first
	exists, err := Backend.Exists(ctx, "Node", node.Metadata.UID)
	if err != nil {
		return fmt.Errorf("failed to check Node existence: %w", err)
	}
	if !exists {
		return fabricaStorage.ErrNotFound
	}

	data, err := json.Marshal(node)
	if err != nil {
		return fmt.Errorf("failed to marshal Node: %w", err)
	}

	if err := Backend.Save(ctx, "Node", node.Metadata.UID, data); err != nil {
		return fmt.Errorf("failed to update Node: %w", err)
	}

	return nil
}

// DeleteNode removes a Node resource by UID.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//   - uid: Unique identifier of the Node resource
//
// Returns:
//   - error: fabricaStorage.ErrNotFound if resource doesn't exist, other errors for failures
func DeleteNode(ctx context.Context, uid string) error {
	ensureBackend()

	if err := Backend.Delete(ctx, "Node", uid); err != nil {
		return fmt.Errorf("failed to delete Node %s: %w", uid, err)
	}

	return nil
}

// ExistsNode checks if a Node resource exists.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//   - uid: Unique identifier of the Node resource
//
// Returns:
//   - bool: true if the resource exists
//   - error: Any error that occurred during the check
func ExistsNode(ctx context.Context, uid string) (bool, error) {
	ensureBackend()

	exists, err := Backend.Exists(ctx, "Node", uid)
	if err != nil {
		return false, fmt.Errorf("failed to check Node existence: %w", err)
	}

	return exists, nil
}

// ListNodeUIDs returns UIDs of all Node resources.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//
// Returns:
//   - []string: Array of Node resource UIDs
//   - error: Any error that occurred during listing
func ListNodeUIDs(ctx context.Context) ([]string, error) {
	ensureBackend()

	uids, err := Backend.List(ctx, "Node")
	if err != nil {
		return nil, fmt.Errorf("failed to list Node UIDs: %w", err)
	}

	return uids, nil
}

// NodeSet storage operations

// LoadAllNodeSets retrieves all NodeSet resources.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//
// Returns:
//   - []*v1.NodeSet: Slice of NodeSet resources
//   - error: Any error that occurred during loading
func LoadAllNodeSets(ctx context.Context) ([]*v1.NodeSet, error) {
	ensureBackend()

	rawData, err := Backend.LoadAll(ctx, "NodeSet")
	if err != nil {
		return nil, fmt.Errorf("failed to load all nodesets: %w", err)
	}

	nodesets := make([]*v1.NodeSet, 0, len(rawData))
	for _, raw := range rawData {
		nodeSet := &v1.NodeSet{}
		if err := json.Unmarshal(raw, nodeSet); err != nil {
			return nil, fmt.Errorf("failed to unmarshal NodeSet: %w", err)
		}
		nodesets = append(nodesets, nodeSet)
	}

	return nodesets, nil
}

// LoadNodeSet retrieves a single NodeSet resource by UID.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//   - uid: Unique identifier of the NodeSet resource
//
// Returns:
//   - *v1.NodeSet: The NodeSet resource
//   - error: fabricaStorage.ErrNotFound if resource doesn't exist, other errors for failures
func LoadNodeSet(ctx context.Context, uid string) (*v1.NodeSet, error) {
ensureBackend()

rawData, err := Backend.Load(ctx, "NodeSet", uid)
if err != nil {
return nil, err
}

nodeSet := &v1.NodeSet{}
if err := json.Unmarshal(rawData, nodeSet); err != nil {
return nil, fmt.Errorf("failed to unmarshal NodeSet: %w", err)
}

return nodeSet, nil
}

// SaveNodeSet stores a NodeSet resource.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//   - nodeSet: The NodeSet resource to save
//
// Returns:
//   - error: Any error that occurred during saving
func SaveNodeSet(ctx context.Context, nodeSet *v1.NodeSet) error {
	ensureBackend()

	data, err := json.Marshal(nodeSet)
	if err != nil {
		return fmt.Errorf("failed to marshal NodeSet: %w", err)
	}

	if err := Backend.Save(ctx, "NodeSet", nodeSet.Metadata.UID, data); err != nil {
		return fmt.Errorf("failed to save NodeSet: %w", err)
	}

	return nil
}

// UpdateNodeSet updates an existing NodeSet resource.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//   - nodeSet: The NodeSet resource to update
//
// Returns:
//   - error: fabricaStorage.ErrNotFound if resource doesn't exist, other errors for failures
func UpdateNodeSet(ctx context.Context, nodeSet *v1.NodeSet) error {
	ensureBackend()

	// Check if resource exists first
	exists, err := Backend.Exists(ctx, "NodeSet", nodeSet.Metadata.UID)
	if err != nil {
		return fmt.Errorf("failed to check NodeSet existence: %w", err)
	}
	if !exists {
		return fabricaStorage.ErrNotFound
	}

	data, err := json.Marshal(nodeSet)
	if err != nil {
		return fmt.Errorf("failed to marshal NodeSet: %w", err)
	}

	if err := Backend.Save(ctx, "NodeSet", nodeSet.Metadata.UID, data); err != nil {
		return fmt.Errorf("failed to update NodeSet: %w", err)
	}

	return nil
}

// DeleteNodeSet removes a NodeSet resource by UID.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//   - uid: Unique identifier of the NodeSet resource
//
// Returns:
//   - error: fabricaStorage.ErrNotFound if resource doesn't exist, other errors for failures
func DeleteNodeSet(ctx context.Context, uid string) error {
	ensureBackend()

	if err := Backend.Delete(ctx, "NodeSet", uid); err != nil {
		return fmt.Errorf("failed to delete NodeSet %s: %w", uid, err)
	}

	return nil
}

// ExistsNodeSet checks if a NodeSet resource exists.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//   - uid: Unique identifier of the NodeSet resource
//
// Returns:
//   - bool: true if the resource exists
//   - error: Any error that occurred during the check
func ExistsNodeSet(ctx context.Context, uid string) (bool, error) {
	ensureBackend()

	exists, err := Backend.Exists(ctx, "NodeSet", uid)
	if err != nil {
		return false, fmt.Errorf("failed to check NodeSet existence: %w", err)
	}

	return exists, nil
}

// ListNodeSetUIDs returns UIDs of all NodeSet resources.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//
// Returns:
//   - []string: Array of NodeSet resource UIDs
//   - error: Any error that occurred during listing
func ListNodeSetUIDs(ctx context.Context) ([]string, error) {
	ensureBackend()

	uids, err := Backend.List(ctx, "NodeSet")
	if err != nil {
		return nil, fmt.Errorf("failed to list NodeSet UIDs: %w", err)
	}

	return uids, nil
}

// ProfileBinding storage operations

// LoadAllProfileBindings retrieves all ProfileBinding resources.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//
// Returns:
//   - []*v1.ProfileBinding: Slice of ProfileBinding resources
//   - error: Any error that occurred during loading
func LoadAllProfileBindings(ctx context.Context) ([]*v1.ProfileBinding, error) {
	ensureBackend()

	rawData, err := Backend.LoadAll(ctx, "ProfileBinding")
	if err != nil {
		return nil, fmt.Errorf("failed to load all profilebindings: %w", err)
	}

	profilebindings := make([]*v1.ProfileBinding, 0, len(rawData))
	for _, raw := range rawData {
		profileBinding := &v1.ProfileBinding{}
		if err := json.Unmarshal(raw, profileBinding); err != nil {
			return nil, fmt.Errorf("failed to unmarshal ProfileBinding: %w", err)
		}
		profilebindings = append(profilebindings, profileBinding)
	}

	return profilebindings, nil
}

// LoadProfileBinding retrieves a single ProfileBinding resource by UID.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//   - uid: Unique identifier of the ProfileBinding resource
//
// Returns:
//   - *v1.ProfileBinding: The ProfileBinding resource
//   - error: fabricaStorage.ErrNotFound if resource doesn't exist, other errors for failures
func LoadProfileBinding(ctx context.Context, uid string) (*v1.ProfileBinding, error) {
	ensureBackend()

	rawData, err := Backend.Load(ctx, "ProfileBinding", uid)
	if err != nil {
		return nil, fmt.Errorf("failed to load ProfileBinding %s: %w", uid, err)
	}

	profileBinding := &v1.ProfileBinding{}
	if err := json.Unmarshal(rawData, profileBinding); err != nil {
		return nil, fmt.Errorf("failed to unmarshal ProfileBinding: %w", err)
	}

	return profileBinding, nil
}

// SaveProfileBinding stores a ProfileBinding resource.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//   - profileBinding: The ProfileBinding resource to save
//
// Returns:
//   - error: Any error that occurred during saving
func SaveProfileBinding(ctx context.Context, profileBinding *v1.ProfileBinding) error {
	ensureBackend()

	data, err := json.Marshal(profileBinding)
	if err != nil {
		return fmt.Errorf("failed to marshal ProfileBinding: %w", err)
	}

	if err := Backend.Save(ctx, "ProfileBinding", profileBinding.Metadata.UID, data); err != nil {
		return fmt.Errorf("failed to save ProfileBinding: %w", err)
	}

	return nil
}

// UpdateProfileBinding updates an existing ProfileBinding resource.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//   - profileBinding: The ProfileBinding resource to update
//
// Returns:
//   - error: fabricaStorage.ErrNotFound if resource doesn't exist, other errors for failures
func UpdateProfileBinding(ctx context.Context, profileBinding *v1.ProfileBinding) error {
	ensureBackend()

	// Check if resource exists first
	exists, err := Backend.Exists(ctx, "ProfileBinding", profileBinding.Metadata.UID)
	if err != nil {
		return fmt.Errorf("failed to check ProfileBinding existence: %w", err)
	}
	if !exists {
		return fabricaStorage.ErrNotFound
	}

	data, err := json.Marshal(profileBinding)
	if err != nil {
		return fmt.Errorf("failed to marshal ProfileBinding: %w", err)
	}

	if err := Backend.Save(ctx, "ProfileBinding", profileBinding.Metadata.UID, data); err != nil {
		return fmt.Errorf("failed to update ProfileBinding: %w", err)
	}

	return nil
}

// DeleteProfileBinding removes a ProfileBinding resource by UID.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//   - uid: Unique identifier of the ProfileBinding resource
//
// Returns:
//   - error: fabricaStorage.ErrNotFound if resource doesn't exist, other errors for failures
func DeleteProfileBinding(ctx context.Context, uid string) error {
	ensureBackend()

	if err := Backend.Delete(ctx, "ProfileBinding", uid); err != nil {
		return fmt.Errorf("failed to delete ProfileBinding %s: %w", uid, err)
	}

	return nil
}

// ExistsProfileBinding checks if a ProfileBinding resource exists.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//   - uid: Unique identifier of the ProfileBinding resource
//
// Returns:
//   - bool: true if the resource exists
//   - error: Any error that occurred during the check
func ExistsProfileBinding(ctx context.Context, uid string) (bool, error) {
	ensureBackend()

	exists, err := Backend.Exists(ctx, "ProfileBinding", uid)
	if err != nil {
		return false, fmt.Errorf("failed to check ProfileBinding existence: %w", err)
	}

	return exists, nil
}

// ListProfileBindingUIDs returns UIDs of all ProfileBinding resources.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//
// Returns:
//   - []string: Array of ProfileBinding resource UIDs
//   - error: Any error that occurred during listing
func ListProfileBindingUIDs(ctx context.Context) ([]string, error) {
	ensureBackend()

	uids, err := Backend.List(ctx, "ProfileBinding")
	if err != nil {
		return nil, fmt.Errorf("failed to list ProfileBinding UIDs: %w", err)
	}

	return uids, nil
}

// StorageClient wraps a StorageBackend to implement reconcile.ClientInterface.
//
// This adapter allows reconcilers to use the storage backend through a
// standard interface that provides typed resource access.
type StorageClient struct {
	backend fabricaStorage.StorageBackend
}

// Compile-time check that StorageClient implements reconcile.ClientInterface
var _ reconcile.ClientInterface = (*StorageClient)(nil)

// NewStorageClient creates a new storage client that wraps the configured backend.
//
// This is used by the reconciliation system to provide reconcilers with
// access to resource storage.
//
// Returns:
//   - *StorageClient: Client that implements reconcile.ClientInterface
func NewStorageClient() *StorageClient {
	ensureBackend()
	return &StorageClient{backend: Backend}
}

// --- Version snapshot helpers (file backend only) ---

// Get retrieves a resource by kind and UID.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//   - kind: Resource kind (e.g., "Device", "Rack")
//   - uid: Unique identifier
//
// Returns:
//   - interface{}: The resource (type-specific)
//   - error: Any error that occurred
func (c *StorageClient) Get(ctx context.Context, kind, uid string) (interface{}, error) {
	rawData, err := c.backend.Load(ctx, kind, uid)
	if err != nil {
		return nil, err
	}

	// Unmarshal based on kind
	switch kind {
	case "Node":
		var resource v1.Node
		if err := json.Unmarshal(rawData, &resource); err != nil {
			return nil, fmt.Errorf("failed to unmarshal Node: %w", err)
		}
		return &resource, nil
	case "NodeSet":
		var resource v1.NodeSet
		if err := json.Unmarshal(rawData, &resource); err != nil {
			return nil, fmt.Errorf("failed to unmarshal NodeSet: %w", err)
		}
		return &resource, nil
	case "ProfileBinding":
		var resource v1.ProfileBinding
		if err := json.Unmarshal(rawData, &resource); err != nil {
			return nil, fmt.Errorf("failed to unmarshal ProfileBinding: %w", err)
		}
		return &resource, nil
	default:
		return nil, fmt.Errorf("unknown resource kind: %s", kind)
	}
}

// List retrieves all resources of a given kind.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//   - kind: Resource kind (e.g., "Device", "Rack")
//
// Returns:
//   - []interface{}: Slice of resources
//   - error: Any error that occurred
func (c *StorageClient) List(ctx context.Context, kind string) ([]interface{}, error) {
	rawData, err := c.backend.LoadAll(ctx, kind)
	if err != nil {
		return nil, err
	}

	// Unmarshal based on kind
	switch kind {
	case "Node":
		result := make([]interface{}, 0, len(rawData))
		for _, raw := range rawData {
			var resource v1.Node
			if err := json.Unmarshal(raw, &resource); err != nil {
				return nil, fmt.Errorf("failed to unmarshal Node: %w", err)
			}
			result = append(result, &resource)
		}
		return result, nil
	case "NodeSet":
		result := make([]interface{}, 0, len(rawData))
		for _, raw := range rawData {
			var resource v1.NodeSet
			if err := json.Unmarshal(raw, &resource); err != nil {
				return nil, fmt.Errorf("failed to unmarshal NodeSet: %w", err)
			}
			result = append(result, &resource)
		}
		return result, nil
	case "ProfileBinding":
		result := make([]interface{}, 0, len(rawData))
		for _, raw := range rawData {
			var resource v1.ProfileBinding
			if err := json.Unmarshal(raw, &resource); err != nil {
				return nil, fmt.Errorf("failed to unmarshal ProfileBinding: %w", err)
			}
			result = append(result, &resource)
		}
		return result, nil
	default:
		return nil, fmt.Errorf("unknown resource kind: %s", kind)
	}
}

// Update updates an existing resource.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//   - resource: The resource to update
//
// Returns:
//   - error: Any error that occurred
func (c *StorageClient) Update(ctx context.Context, resource interface{}) error {
	data, err := json.Marshal(resource)
	if err != nil {
		return fmt.Errorf("failed to marshal resource: %w", err)
	}

	// Extract kind and UID based on type
	switch res := resource.(type) {
	case *v1.Node:
		return c.backend.Save(ctx, "Node", res.Metadata.UID, data)
	case *v1.NodeSet:
		return c.backend.Save(ctx, "NodeSet", res.Metadata.UID, data)
	case *v1.ProfileBinding:
		return c.backend.Save(ctx, "ProfileBinding", res.Metadata.UID, data)
	default:
		return fmt.Errorf("unknown resource type: %T", resource)
	}
}

// Create creates a new resource.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//   - resource: The resource to create
//
// Returns:
//   - error: Any error that occurred
func (c *StorageClient) Create(ctx context.Context, resource interface{}) error {
	// For storage backend, Create is the same as Update (Save handles both)
	return c.Update(ctx, resource)
}

// Delete deletes a resource by kind and UID.
//
// Parameters:
//   - ctx: Context for cancellation and timeouts
//   - kind: Resource kind
//   - uid: Unique identifier
//
// Returns:
//   - error: Any error that occurred
func (c *StorageClient) Delete(ctx context.Context, kind, uid string) error {
	return c.backend.Delete(ctx, kind, uid)
}
