// Code generated by fabrica. DO NOT EDIT.
package resources

import (
	"fmt"

	"github.com/openchami/fabrica/pkg/codegen"
	v1 "github.com/user/node-service/apis/example.fabrica.dev/v1"
)

// RegisterAllResources registers all discovered resources with the generator.
// This file is auto-generated. Re-run 'fabrica generate' after adding resources.
func RegisterAllResources(gen *codegen.Generator) error {
	if err := gen.RegisterResource(&v1.Campaign{}); err != nil {
		return fmt.Errorf("failed to register Campaign: %w", err)
	}
	if err := gen.RegisterResource(&v1.Node{}); err != nil {
		return fmt.Errorf("failed to register Node: %w", err)
	}
	if err := gen.RegisterResource(&v1.NodeSet{}); err != nil {
		return fmt.Errorf("failed to register NodeSet: %w", err)
	}
	if err := gen.RegisterResource(&v1.ProfileBinding{}); err != nil {
		return fmt.Errorf("failed to register ProfileBinding: %w", err)
	}

	return nil
}
