// Code generated by Fabrica dev. DO NOT EDIT.
// Copyright © 2025 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT
//
// This file contains request/response models for REST API operations.
// Generated from: pkg/codegen/templates/models.go.tmpl
//
// To modify request/response models:
//  1. Edit the template file: pkg/codegen/templates/models.go.tmpl
//  2. Run 'make dev' to regenerate
//  3. Do NOT edit this file directly - changes will be lost
//
// Generated models for each resource:
//   - ResourceResponse: Single resource response (alias to resource type)
//   - ResourcesResponse: List of resources with pagination info
//   - CreateResourceRequest: Create operation request body
//   - UpdateResourceRequest: Update operation request body
//   - DeleteResponse: Delete operation response
//
// Request structure:
//   - Embeds resource Spec fields inline (json:",inline")
//   - Includes metadata fields (Name, Labels, Annotations)
//   - Uses validation tags for required fields
//
// To add custom validation:
//  1. Add validation tags to template (e.g., validate:"required,email")
//  2. Implement validation middleware in handlers
//
// To add additional fields:
//  1. Modify Create/Update request structs in template
//  2. Update corresponding handlers to process new fields
package main

import (
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/openchami/fabrica/pkg/fabrica"

	"github.com/user/node-service/apis/example.fabrica.dev/v1"
)

// CampaignResponse represents the response for Campaign operations
type CampaignResponse = v1.Campaign

// CreateCampaignRequest represents a request to create a Campaign
type CreateCampaignRequest struct {
	Metadata    fabrica.Metadata  `json:"metadata" validate:"required"`
	Spec        v1.CampaignSpec   `json:"spec" validate:"required"`
	Labels      map[string]string `json:"labels,omitempty"`
	Annotations map[string]string `json:"annotations,omitempty"`
}

// AsSpec converts the request fields to a spec object
func (r *CreateCampaignRequest) AsSpec() v1.CampaignSpec {
	return r.Spec
}

// UpdateCampaignRequest represents a request to update a Campaign
type UpdateCampaignRequest struct {
	Metadata    fabrica.Metadata  `json:"metadata,omitempty"`
	Spec        v1.CampaignSpec   `json:"spec,omitempty" validate:"omitempty"`
	Labels      map[string]string `json:"labels,omitempty"`
	Annotations map[string]string `json:"annotations,omitempty"`
}

// AsSpec converts the request fields to a spec object
func (r *UpdateCampaignRequest) AsSpec() v1.CampaignSpec {
	return r.Spec
}

// NodeResponse represents the response for Node operations
type NodeResponse = v1.Node

// CreateNodeRequest represents a request to create a Node
type CreateNodeRequest struct {
	Metadata    fabrica.Metadata  `json:"metadata" validate:"required"`
	Spec        v1.NodeSpec       `json:"spec" validate:"required"`
	Labels      map[string]string `json:"labels,omitempty"`
	Annotations map[string]string `json:"annotations,omitempty"`
}

// AsSpec converts the request fields to a spec object
func (r *CreateNodeRequest) AsSpec() v1.NodeSpec {
	return r.Spec
}

// UpdateNodeRequest represents a request to update a Node
type UpdateNodeRequest struct {
	Metadata    fabrica.Metadata  `json:"metadata,omitempty"`
	Spec        v1.NodeSpec       `json:"spec,omitempty" validate:"omitempty"`
	Labels      map[string]string `json:"labels,omitempty"`
	Annotations map[string]string `json:"annotations,omitempty"`
}

// AsSpec converts the request fields to a spec object
func (r *UpdateNodeRequest) AsSpec() v1.NodeSpec {
	return r.Spec
}

// NodeSetResponse represents the response for NodeSet operations
type NodeSetResponse = v1.NodeSet

// CreateNodeSetRequest represents a request to create a NodeSet
type CreateNodeSetRequest struct {
	Metadata    fabrica.Metadata  `json:"metadata" validate:"required"`
	Spec        v1.NodeSetSpec    `json:"spec" validate:"required"`
	Labels      map[string]string `json:"labels,omitempty"`
	Annotations map[string]string `json:"annotations,omitempty"`
}

// AsSpec converts the request fields to a spec object
func (r *CreateNodeSetRequest) AsSpec() v1.NodeSetSpec {
	return r.Spec
}

// UpdateNodeSetRequest represents a request to update a NodeSet
type UpdateNodeSetRequest struct {
	Metadata    fabrica.Metadata  `json:"metadata,omitempty"`
	Spec        v1.NodeSetSpec    `json:"spec,omitempty" validate:"omitempty"`
	Labels      map[string]string `json:"labels,omitempty"`
	Annotations map[string]string `json:"annotations,omitempty"`
}

// AsSpec converts the request fields to a spec object
func (r *UpdateNodeSetRequest) AsSpec() v1.NodeSetSpec {
	return r.Spec
}

// ProfileBindingResponse represents the response for ProfileBinding operations
type ProfileBindingResponse = v1.ProfileBinding

// CreateProfileBindingRequest represents a request to create a ProfileBinding
type CreateProfileBindingRequest struct {
	Metadata    fabrica.Metadata      `json:"metadata" validate:"required"`
	Spec        v1.ProfileBindingSpec `json:"spec" validate:"required"`
	Labels      map[string]string     `json:"labels,omitempty"`
	Annotations map[string]string     `json:"annotations,omitempty"`
}

// AsSpec converts the request fields to a spec object
func (r *CreateProfileBindingRequest) AsSpec() v1.ProfileBindingSpec {
	return r.Spec
}

// UpdateProfileBindingRequest represents a request to update a ProfileBinding
type UpdateProfileBindingRequest struct {
	Metadata    fabrica.Metadata      `json:"metadata,omitempty"`
	Spec        v1.ProfileBindingSpec `json:"spec,omitempty" validate:"omitempty"`
	Labels      map[string]string     `json:"labels,omitempty"`
	Annotations map[string]string     `json:"annotations,omitempty"`
}

// AsSpec converts the request fields to a spec object
func (r *UpdateProfileBindingRequest) AsSpec() v1.ProfileBindingSpec {
	return r.Spec
}

// ErrorResponse represents an error response
type ErrorResponse struct {
	Error   string `json:"error"`
	Message string `json:"message,omitempty"`
	Code    int    `json:"code,omitempty"`
}

// DeleteResponse represents a successful deletion response
type DeleteResponse struct {
	Message string `json:"message"`
	UID     string `json:"uid"`
}

// Helper functions for handlers

// respondJSON sends a JSON response
func respondJSON(w http.ResponseWriter, status int, data interface{}) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	if err := json.NewEncoder(w).Encode(data); err != nil {
		http.Error(w, fmt.Sprintf("failed to encode response: %v", err), http.StatusInternalServerError)
	}
}

// respondError sends an error response
func respondError(w http.ResponseWriter, status int, err error) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	response := ErrorResponse{
		Error: err.Error(),
		Code:  status,
	}
	json.NewEncoder(w).Encode(response)
}
