// Code generated by Fabrica dev. DO NOT EDIT.
// Template: server/handlers.go.tmpl
// Generated: 2026-03-26T10:35:55-07:00
//
// # Copyright © 2025 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT
//
// This file contains REST API handlers for NodeSet resources.
//
// To modify this code:
//  1. Edit the template file: pkg/codegen/templates/handlers.go.tmpl
//  2. Run 'make dev' to regenerate
//  3. Do NOT edit this file directly - changes will be lost
//
// Generated handlers provide:
//   - GET /nodesets (list all nodesets)
//   - GET /nodesets/{uid} (get specific NodeSet)
//   - POST /nodesets (create new NodeSet)
//   - PUT /nodesets/{uid} (update NodeSet spec)
//   - PATCH /nodesets/{uid} (patch NodeSet spec)
//   - DELETE /nodesets/{uid} (delete NodeSet)
//   - PUT /nodesets/{uid}/status (update NodeSet status)
//   - PATCH /nodesets/{uid}/status (patch NodeSet status)
//
// Authorization: Add custom middleware for authentication/authorization
// Storage: Uses storage.LoadNodeSet*/SaveNodeSet*/DeleteNodeSet*
// Version Support: Available (see version context in handlers)
//
// To enable full version conversion for this resource:
//  1. Add new version: fabrica add version <group> <version>
//  2. Implement converter: apis/<group>/<version>/converter.go
//  3. Add version-aware storage: storage.LoadNodeSetWithVersion()
//  4. Register versions in cmd/server/main.go
package main

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/openchami/fabrica/pkg/events"
	"github.com/openchami/fabrica/pkg/patch"
	"github.com/openchami/fabrica/pkg/resource"
	"github.com/openchami/fabrica/pkg/validation"
	"github.com/openchami/fabrica/pkg/versioning"
	v1 "github.com/user/node-service/apis/example.fabrica.dev/v1"

	"github.com/user/node-service/internal/storage"
)

// GetNodeSets returns all NodeSet resources
func GetNodeSets(w http.ResponseWriter, r *http.Request) {
// Authorization: Add custom middleware in routes.go or implement checks here
// Example: if !authorized(r) { respondError(w, http.StatusUnauthorized, fmt.Errorf("unauthorized")); return }

nodesets, err := storage.ListNodeSets(r.Context())
if err != nil {
respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to load nodesets: %w", err))
return
}
respondJSON(w, http.StatusOK, nodesets)
}

// GetNodeSet returns a specific NodeSet resource by UID
func GetNodeSet(w http.ResponseWriter, r *http.Request) {
uid := chi.URLParam(r, "uid")
if uid == "" {
respondError(w, http.StatusBadRequest, fmt.Errorf("NodeSet UID is required"))
return
}

// Version context available here for version-aware operations
// versionCtx := versioning.GetVersionContext(r.Context())
// Requested version: versionCtx.ServeVersion
// To enable: replace storage.LoadNodeSet() with version-aware function

// Authorization: Add custom middleware in routes.go or implement checks here
// Example: if !authorized(r) { respondError(w, http.StatusUnauthorized, fmt.Errorf("unauthorized")); return }

nodeSet, err := storage.GetNodeSet(r.Context(), uid)
if err != nil {
respondError(w, http.StatusNotFound, fmt.Errorf("NodeSet not found: %w", err))
return
}
respondJSON(w, http.StatusOK, nodeSet)
}

// CreateNodeSet creates a new NodeSet resource
func CreateNodeSet(w http.ResponseWriter, r *http.Request) {
var req CreateNodeSetRequest
if r.Body == nil {
respondError(w, http.StatusBadRequest, fmt.Errorf("request body is empty"))
return
}
if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
respondError(w, http.StatusBadRequest, fmt.Errorf("invalid request body: %w", err))
return
}

	// Layer 1: Request validation (validates inline spec fields and metadata)
	if err := validation.ValidateResource(&req); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("validation failed: %w", err))
		return
	}

	// Get version context from request (set by version negotiation middleware)
	versionCtx := versioning.GetVersionContext(r.Context())

	uid, err := resource.GenerateUIDForResource("NodeSet")
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to generate UID: %w", err))
		return
	}

	// Versioned mode: flat fields with fabrica.Metadata
	nodeSet := &v1.NodeSet{
		// Use negotiated ServeVersion (from Accept header) for apiVersion
		APIVersion: versionCtx.ServeVersion,
		Kind:       "NodeSet",
		Spec:       req.AsSpec(),
	}

	// Initialize metadata from request
	nodeSet.Metadata = req.Metadata
	nodeSet.Metadata.UID = uid
	now := time.Now()
	nodeSet.Metadata.CreatedAt = now
	nodeSet.Metadata.UpdatedAt = now

	// Set labels and annotations
	if nodeSet.Metadata.Labels == nil {
		nodeSet.Metadata.Labels = make(map[string]string)
	}
	for k, v := range req.Labels {
		nodeSet.Metadata.Labels[k] = v
	}
	if nodeSet.Metadata.Annotations == nil {
		nodeSet.Metadata.Annotations = make(map[string]string)
	}
	for k, v := range req.Annotations {
		nodeSet.Metadata.Annotations[k] = v
	}

	// Layer 2: Custom business logic validation
	if err := validation.ValidateWithContext(r.Context(), nodeSet); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("validation failed: %w", err))
		return
	}

	// Set initial status
	// This assumes the generator passes an 'IsReconcilable' boolean
	// to this template, and that the resource has a .Status.Phase field.

	// Save (Layer 1: Ent validation happens automatically if using Ent storage)
	if err := storage.SaveNodeSet(r.Context(), nodeSet); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save NodeSet: %w", err))
		return
	}

	// Publish resource created event

	if err := events.PublishResourceCreated(r.Context(), "NodeSet", nodeSet.Metadata.UID, nodeSet.Metadata.Name, nodeSet); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource created event for NodeSet %s: %v\n", nodeSet.Metadata.UID, err)

	}

	respondJSON(w, http.StatusCreated, nodeSet)
}

// UpdateNodeSet updates the spec of an existing NodeSet resource
// NOTE: This endpoint ONLY updates the spec. Use PUT //nodesets/{uid}/status to update status.
func UpdateNodeSet(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("NodeSet UID is required"))
		return
	}

	nodeSet, err := storage.LoadNodeSet(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("NodeSet not found: %w", err))
		return
	}

	var req UpdateNodeSetRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("invalid request body: %w", err))
		return
	}

	// Apply updates

	// Versioned mode: direct field access
	if req.Metadata.Name != "" {
		nodeSet.Metadata.Name = req.Metadata.Name
	}

	// Update spec fields ONLY - status should use /status subresource
	nodeSet.Spec = req.AsSpec()

	// Update labels and annotations
	if nodeSet.Metadata.Labels == nil {
		nodeSet.Metadata.Labels = make(map[string]string)
	}
	for k, v := range req.Labels {
		nodeSet.Metadata.Labels[k] = v
	}
	if nodeSet.Metadata.Annotations == nil {
		nodeSet.Metadata.Annotations = make(map[string]string)
	}
	for k, v := range req.Annotations {
		nodeSet.Metadata.Annotations[k] = v
	}

	// Update timestamp
	nodeSet.Metadata.UpdatedAt = time.Now()

	if err := storage.SaveNodeSet(r.Context(), nodeSet); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save NodeSet: %w", err))
		return
	}

	// Publish resource updated event
	updateMetadata := map[string]interface{}{
		"updatedAt": nodeSet.Metadata.UpdatedAt,
	}

	if err := events.PublishResourceUpdated(r.Context(), "NodeSet", nodeSet.Metadata.UID, nodeSet.Metadata.Name, nodeSet, updateMetadata); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource updated event for NodeSet %s: %v\n", nodeSet.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, nodeSet)
}

// PatchNodeSet patches an existing NodeSet resource spec using JSON Merge Patch, JSON Patch, or Shorthand Patch
// Only the spec portion of the resource can be patched - metadata and status are API-managed
func PatchNodeSet(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("NodeSet UID is required"))
		return
	}

	nodeSet, err := storage.LoadNodeSet(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("NodeSet not found: %w", err))
		return
	}

	// Read patch document
	patchData, err := io.ReadAll(r.Body)
	if err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("failed to read patch data: %w", err))
		return
	}

	// Marshal current spec to JSON for patching (only allow spec modifications)
	currentSpecJSON, err := json.Marshal(nodeSet.Spec)
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to marshal current spec: %w", err))
		return
	}

	// Detect patch type from Content-Type header
	contentType := r.Header.Get("Content-Type")
	patchType := patch.DetectPatchType(contentType)

	// Apply patch to spec only
	patchResult, err := patch.ApplyPatchWithOptions(currentSpecJSON, patchData, patchType, patch.PatchOptions{
		AllowAddFields:    true,
		AllowRemoveFields: true,
	})
	if err != nil {
		respondError(w, http.StatusUnprocessableEntity, fmt.Errorf("failed to apply patch to spec: %w", err))
		return
	}

	// Unmarshal the patched result back to the spec
	if err := json.Unmarshal(patchResult.Updated, &nodeSet.Spec); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to unmarshal patched spec: %w", err))
		return
	}

	// Touch to update metadata

	nodeSet.Metadata.UpdatedAt = time.Now()

	// Save the patched resource
	if err := storage.SaveNodeSet(r.Context(), nodeSet); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save patched NodeSet: %w", err))
		return
	}

	// Publish resource patched event
	patchMetadata := map[string]interface{}{
		"patchType": patchType,
		"updatedAt": nodeSet.Metadata.UpdatedAt,
	}

	if err := events.PublishResourcePatched(r.Context(), "NodeSet", nodeSet.Metadata.UID, nodeSet.Metadata.Name, nodeSet, patchMetadata); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource patched event for NodeSet %s: %v\n", nodeSet.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, nodeSet)
}

// UpdateNodeSetStatus updates only the status of a NodeSet resource
// This endpoint is intended for controllers, reconcilers, and monitoring systems.
// It does not modify the spec or metadata (except updatedAt timestamp).
//
// Authorization: Requires 'update_status' permission (separate from 'update' permission)
// Events: Publishes resource updated event with updateType: "status"
func UpdateNodeSetStatus(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("NodeSet UID is required"))
		return
	}

	// Authorization: Add custom middleware for status update authorization
	// Status updates can have different permissions than spec updates

	res, err := storage.LoadNodeSet(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("NodeSet not found: %w", err))
		return
	}

	var statusUpdate v1.NodeSetStatus
	if err := json.NewDecoder(r.Body).Decode(&statusUpdate); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("invalid status body: %w", err))
		return
	}

	// Preserve spec - only update status
	res.Status = statusUpdate

	res.Metadata.UpdatedAt = time.Now()

	if err := storage.SaveNodeSet(r.Context(), res); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save NodeSet status: %w", err))
		return
	}

	// Publish status update event
	statusMetadata := map[string]interface{}{
		"updatedAt":  res.Metadata.UpdatedAt,
		"updateType": "status",
	}

	if err := events.PublishResourceUpdated(r.Context(), "NodeSet", res.Metadata.UID, res.Metadata.Name, res, statusMetadata); err != nil {
		// Log but don't fail - events are non-critical
		fmt.Printf("Warning: Failed to publish status update event for NodeSet %s: %v\n", res.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, res)
}

// PatchNodeSetStatus patches only the status of a NodeSet resource
// Supports JSON Merge Patch, JSON Patch, and Shorthand Patch formats.
// Only modifies status fields - spec and metadata are preserved.
func PatchNodeSetStatus(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("NodeSet UID is required"))
		return
	}

	// Authorization: Add custom middleware for status patch authorization
	// Status patches can have different permissions than spec patches

	res, err := storage.LoadNodeSet(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("NodeSet not found: %w", err))
		return
	}

	patchData, err := io.ReadAll(r.Body)
	if err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("failed to read patch data: %w", err))
		return
	}

	// Marshal current status for patching
	currentStatusJSON, err := json.Marshal(res.Status)
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to marshal current status: %w", err))
		return
	}

	contentType := r.Header.Get("Content-Type")
	patchType := patch.DetectPatchType(contentType)

	patchResult, err := patch.ApplyPatchWithOptions(currentStatusJSON, patchData, patchType, patch.PatchOptions{
		AllowAddFields:    true,
		AllowRemoveFields: false, // Don't allow removing status fields
	})
	if err != nil {
		respondError(w, http.StatusUnprocessableEntity, fmt.Errorf("failed to apply patch to status: %w", err))
		return
	}

	// Unmarshal patched status back
	if err := json.Unmarshal(patchResult.Updated, &res.Status); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to unmarshal patched status: %w", err))
		return
	}

	res.Metadata.UpdatedAt = time.Now()

	if err := storage.SaveNodeSet(r.Context(), res); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save patched NodeSet status: %w", err))
		return
	}

	// Publish status patch event
	patchMetadata := map[string]interface{}{
		"patchType":  patchType,
		"updatedAt":  res.Metadata.UpdatedAt,
		"updateType": "status",
	}

	if err := events.PublishResourcePatched(r.Context(), "NodeSet", res.Metadata.UID, res.Metadata.Name, res, patchMetadata); err != nil {
		fmt.Printf("Warning: Failed to publish status patch event for NodeSet %s: %v\n", res.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, res)
}

// DeleteNodeSet deletes a NodeSet resource
func DeleteNodeSet(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("NodeSet UID is required"))
		return
	}

	// Load resource before deletion for event publishing
	nodeSet, err := storage.LoadNodeSet(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("NodeSet not found: %w", err))
		return
	}

	if err := storage.DeleteNodeSet(r.Context(), uid); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to delete NodeSet: %w", err))
		return
	}

	// Publish resource deleted event
	deleteMetadata := map[string]interface{}{
		"deletedAt": time.Now(),
	}

	if err := events.PublishResourceDeleted(r.Context(), "NodeSet", nodeSet.Metadata.UID, nodeSet.Metadata.Name, deleteMetadata); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource deleted event for NodeSet %s: %v\n", nodeSet.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, &DeleteResponse{
		Message: "NodeSet deleted successfully",
		UID:     uid,
	})
}
