// Code generated by Fabrica dev. DO NOT EDIT.
// Template: server/handlers.go.tmpl
// Generated: 2026-03-26T10:35:55-07:00
//
// # Copyright © 2025 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT
//
// This file contains REST API handlers for ProfileBinding resources.
//
// To modify this code:
//  1. Edit the template file: pkg/codegen/templates/handlers.go.tmpl
//  2. Run 'make dev' to regenerate
//  3. Do NOT edit this file directly - changes will be lost
//
// Generated handlers provide:
//   - GET /profilebindings (list all profilebindings)
//   - GET /profilebindings/{uid} (get specific ProfileBinding)
//   - POST /profilebindings (create new ProfileBinding)
//   - PUT /profilebindings/{uid} (update ProfileBinding spec)
//   - PATCH /profilebindings/{uid} (patch ProfileBinding spec)
//   - DELETE /profilebindings/{uid} (delete ProfileBinding)
//   - PUT /profilebindings/{uid}/status (update ProfileBinding status)
//   - PATCH /profilebindings/{uid}/status (patch ProfileBinding status)
//
// Authorization: Add custom middleware for authentication/authorization
// Storage: Uses storage.LoadProfileBinding*/SaveProfileBinding*/DeleteProfileBinding*
// Version Support: Available (see version context in handlers)
//
// To enable full version conversion for this resource:
//  1. Add new version: fabrica add version <group> <version>
//  2. Implement converter: apis/<group>/<version>/converter.go
//  3. Add version-aware storage: storage.LoadProfileBindingWithVersion()
//  4. Register versions in cmd/server/main.go
package main

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/openchami/fabrica/pkg/events"
	"github.com/openchami/fabrica/pkg/patch"
	"github.com/openchami/fabrica/pkg/resource"
	"github.com/openchami/fabrica/pkg/validation"
	"github.com/openchami/fabrica/pkg/versioning"
	v1 "github.com/user/node-service/apis/example.fabrica.dev/v1"

	"github.com/user/node-service/internal/storage"
)

// GetProfileBindings returns all ProfileBinding resources
func GetProfileBindings(w http.ResponseWriter, r *http.Request) {
	// Authorization: Add custom middleware in routes.go or implement checks here
	// Example: if !authorized(r) { respondError(w, http.StatusUnauthorized, fmt.Errorf("unauthorized")); return }

	profilebindings, err := storage.LoadAllProfileBindings(r.Context())
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to load profilebindings: %w", err))
		return
	}
	respondJSON(w, http.StatusOK, profilebindings)
}

// GetProfileBinding returns a specific ProfileBinding resource by UID
func GetProfileBinding(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("ProfileBinding UID is required"))
		return
	}

	// Version context available here for version-aware operations
	// versionCtx := versioning.GetVersionContext(r.Context())
	// Requested version: versionCtx.ServeVersion
	// To enable: replace storage.LoadProfileBinding() with version-aware function

	// Authorization: Add custom middleware in routes.go or implement checks here
	// Example: if !authorized(r) { respondError(w, http.StatusUnauthorized, fmt.Errorf("unauthorized")); return }

	profileBinding, err := storage.LoadProfileBinding(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("ProfileBinding not found: %w", err))
		return
	}
	respondJSON(w, http.StatusOK, profileBinding)
}

// CreateProfileBinding creates a new ProfileBinding resource
func CreateProfileBinding(w http.ResponseWriter, r *http.Request) {
	var req CreateProfileBindingRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("invalid request body: %w", err))
		return
	}

	// Layer 1: Request validation (validates inline spec fields and metadata)
	if err := validation.ValidateResource(&req); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("validation failed: %w", err))
		return
	}

	// Get version context from request (set by version negotiation middleware)
	versionCtx := versioning.GetVersionContext(r.Context())

	uid, err := resource.GenerateUIDForResource("ProfileBinding")
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to generate UID: %w", err))
		return
	}

	// Versioned mode: flat fields with fabrica.Metadata
	profileBinding := &v1.ProfileBinding{
		// Use negotiated ServeVersion (from Accept header) for apiVersion
		APIVersion: versionCtx.ServeVersion,
		Kind:       "ProfileBinding",
		Spec:       req.AsSpec(),
	}

	// Initialize metadata from request
	profileBinding.Metadata = req.Metadata
	profileBinding.Metadata.UID = uid
	now := time.Now()
	profileBinding.Metadata.CreatedAt = now
	profileBinding.Metadata.UpdatedAt = now

	// Set labels and annotations
	if profileBinding.Metadata.Labels == nil {
		profileBinding.Metadata.Labels = make(map[string]string)
	}
	for k, v := range req.Labels {
		profileBinding.Metadata.Labels[k] = v
	}
	if profileBinding.Metadata.Annotations == nil {
		profileBinding.Metadata.Annotations = make(map[string]string)
	}
	for k, v := range req.Annotations {
		profileBinding.Metadata.Annotations[k] = v
	}

	// Layer 2: Custom business logic validation
	if err := validation.ValidateWithContext(r.Context(), profileBinding); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("validation failed: %w", err))
		return
	}

	// Set initial status
	// This assumes the generator passes an 'IsReconcilable' boolean
	// to this template, and that the resource has a .Status.Phase field.

	// Save (Layer 1: Ent validation happens automatically if using Ent storage)
	if err := storage.SaveProfileBinding(r.Context(), profileBinding); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save ProfileBinding: %w", err))
		return
	}

	// Publish resource created event

	if err := events.PublishResourceCreated(r.Context(), "ProfileBinding", profileBinding.Metadata.UID, profileBinding.Metadata.Name, profileBinding); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource created event for ProfileBinding %s: %v\n", profileBinding.Metadata.UID, err)

	}

	respondJSON(w, http.StatusCreated, profileBinding)
}

// UpdateProfileBinding updates the spec of an existing ProfileBinding resource
// NOTE: This endpoint ONLY updates the spec. Use PUT //profilebindings/{uid}/status to update status.
func UpdateProfileBinding(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("ProfileBinding UID is required"))
		return
	}

	profileBinding, err := storage.LoadProfileBinding(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("ProfileBinding not found: %w", err))
		return
	}

	var req UpdateProfileBindingRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("invalid request body: %w", err))
		return
	}

	// Apply updates

	// Versioned mode: direct field access
	if req.Metadata.Name != "" {
		profileBinding.Metadata.Name = req.Metadata.Name
	}

	// Update spec fields ONLY - status should use /status subresource
	profileBinding.Spec = req.AsSpec()

	// Update labels and annotations
	if profileBinding.Metadata.Labels == nil {
		profileBinding.Metadata.Labels = make(map[string]string)
	}
	for k, v := range req.Labels {
		profileBinding.Metadata.Labels[k] = v
	}
	if profileBinding.Metadata.Annotations == nil {
		profileBinding.Metadata.Annotations = make(map[string]string)
	}
	for k, v := range req.Annotations {
		profileBinding.Metadata.Annotations[k] = v
	}

	// Update timestamp
	profileBinding.Metadata.UpdatedAt = time.Now()

	if err := storage.SaveProfileBinding(r.Context(), profileBinding); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save ProfileBinding: %w", err))
		return
	}

	// Publish resource updated event
	updateMetadata := map[string]interface{}{
		"updatedAt": profileBinding.Metadata.UpdatedAt,
	}

	if err := events.PublishResourceUpdated(r.Context(), "ProfileBinding", profileBinding.Metadata.UID, profileBinding.Metadata.Name, profileBinding, updateMetadata); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource updated event for ProfileBinding %s: %v\n", profileBinding.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, profileBinding)
}

// PatchProfileBinding patches an existing ProfileBinding resource spec using JSON Merge Patch, JSON Patch, or Shorthand Patch
// Only the spec portion of the resource can be patched - metadata and status are API-managed
func PatchProfileBinding(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("ProfileBinding UID is required"))
		return
	}

	profileBinding, err := storage.LoadProfileBinding(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("ProfileBinding not found: %w", err))
		return
	}

	// Read patch document
	patchData, err := io.ReadAll(r.Body)
	if err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("failed to read patch data: %w", err))
		return
	}

	// Marshal current spec to JSON for patching (only allow spec modifications)
	currentSpecJSON, err := json.Marshal(profileBinding.Spec)
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to marshal current spec: %w", err))
		return
	}

	// Detect patch type from Content-Type header
	contentType := r.Header.Get("Content-Type")
	patchType := patch.DetectPatchType(contentType)

	// Apply patch to spec only
	patchResult, err := patch.ApplyPatchWithOptions(currentSpecJSON, patchData, patchType, patch.PatchOptions{
		AllowAddFields:    true,
		AllowRemoveFields: true,
	})
	if err != nil {
		respondError(w, http.StatusUnprocessableEntity, fmt.Errorf("failed to apply patch to spec: %w", err))
		return
	}

	// Unmarshal the patched result back to the spec
	if err := json.Unmarshal(patchResult.Updated, &profileBinding.Spec); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to unmarshal patched spec: %w", err))
		return
	}

	// Touch to update metadata

	profileBinding.Metadata.UpdatedAt = time.Now()

	// Save the patched resource
	if err := storage.SaveProfileBinding(r.Context(), profileBinding); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save patched ProfileBinding: %w", err))
		return
	}

	// Publish resource patched event
	patchMetadata := map[string]interface{}{
		"patchType": patchType,
		"updatedAt": profileBinding.Metadata.UpdatedAt,
	}

	if err := events.PublishResourcePatched(r.Context(), "ProfileBinding", profileBinding.Metadata.UID, profileBinding.Metadata.Name, profileBinding, patchMetadata); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource patched event for ProfileBinding %s: %v\n", profileBinding.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, profileBinding)
}

// UpdateProfileBindingStatus updates only the status of a ProfileBinding resource
// This endpoint is intended for controllers, reconcilers, and monitoring systems.
// It does not modify the spec or metadata (except updatedAt timestamp).
//
// Authorization: Requires 'update_status' permission (separate from 'update' permission)
// Events: Publishes resource updated event with updateType: "status"
func UpdateProfileBindingStatus(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("ProfileBinding UID is required"))
		return
	}

	// Authorization: Add custom middleware for status update authorization
	// Status updates can have different permissions than spec updates

	res, err := storage.LoadProfileBinding(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("ProfileBinding not found: %w", err))
		return
	}

	var statusUpdate v1.ProfileBindingStatus
	if err := json.NewDecoder(r.Body).Decode(&statusUpdate); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("invalid status body: %w", err))
		return
	}

	// Preserve spec - only update status
	res.Status = statusUpdate

	res.Metadata.UpdatedAt = time.Now()

	if err := storage.SaveProfileBinding(r.Context(), res); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save ProfileBinding status: %w", err))
		return
	}

	// Publish status update event
	statusMetadata := map[string]interface{}{
		"updatedAt":  res.Metadata.UpdatedAt,
		"updateType": "status",
	}

	if err := events.PublishResourceUpdated(r.Context(), "ProfileBinding", res.Metadata.UID, res.Metadata.Name, res, statusMetadata); err != nil {
		// Log but don't fail - events are non-critical
		fmt.Printf("Warning: Failed to publish status update event for ProfileBinding %s: %v\n", res.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, res)
}

// PatchProfileBindingStatus patches only the status of a ProfileBinding resource
// Supports JSON Merge Patch, JSON Patch, and Shorthand Patch formats.
// Only modifies status fields - spec and metadata are preserved.
func PatchProfileBindingStatus(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("ProfileBinding UID is required"))
		return
	}

	// Authorization: Add custom middleware for status patch authorization
	// Status patches can have different permissions than spec patches

	res, err := storage.LoadProfileBinding(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("ProfileBinding not found: %w", err))
		return
	}

	patchData, err := io.ReadAll(r.Body)
	if err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("failed to read patch data: %w", err))
		return
	}

	// Marshal current status for patching
	currentStatusJSON, err := json.Marshal(res.Status)
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to marshal current status: %w", err))
		return
	}

	contentType := r.Header.Get("Content-Type")
	patchType := patch.DetectPatchType(contentType)

	patchResult, err := patch.ApplyPatchWithOptions(currentStatusJSON, patchData, patchType, patch.PatchOptions{
		AllowAddFields:    true,
		AllowRemoveFields: false, // Don't allow removing status fields
	})
	if err != nil {
		respondError(w, http.StatusUnprocessableEntity, fmt.Errorf("failed to apply patch to status: %w", err))
		return
	}

	// Unmarshal patched status back
	if err := json.Unmarshal(patchResult.Updated, &res.Status); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to unmarshal patched status: %w", err))
		return
	}

	res.Metadata.UpdatedAt = time.Now()

	if err := storage.SaveProfileBinding(r.Context(), res); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save patched ProfileBinding status: %w", err))
		return
	}

	// Publish status patch event
	patchMetadata := map[string]interface{}{
		"patchType":  patchType,
		"updatedAt":  res.Metadata.UpdatedAt,
		"updateType": "status",
	}

	if err := events.PublishResourcePatched(r.Context(), "ProfileBinding", res.Metadata.UID, res.Metadata.Name, res, patchMetadata); err != nil {
		fmt.Printf("Warning: Failed to publish status patch event for ProfileBinding %s: %v\n", res.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, res)
}

// DeleteProfileBinding deletes a ProfileBinding resource
func DeleteProfileBinding(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("ProfileBinding UID is required"))
		return
	}

	// Load resource before deletion for event publishing
	profileBinding, err := storage.LoadProfileBinding(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("ProfileBinding not found: %w", err))
		return
	}

	if err := storage.DeleteProfileBinding(r.Context(), uid); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to delete ProfileBinding: %w", err))
		return
	}

	// Publish resource deleted event
	deleteMetadata := map[string]interface{}{
		"deletedAt": time.Now(),
	}

	if err := events.PublishResourceDeleted(r.Context(), "ProfileBinding", profileBinding.Metadata.UID, profileBinding.Metadata.Name, deleteMetadata); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource deleted event for ProfileBinding %s: %v\n", profileBinding.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, &DeleteResponse{
		Message: "ProfileBinding deleted successfully",
		UID:     uid,
	})
}
