// Code generated by codegen. DO NOT EDIT.
// Copyright © 2025 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT
//
// This file contains REST API route registrations for all resources.
// Generated from: pkg/codegen/templates/routes.go.tmpl
//
// To modify route registration:
//  1. Edit the template file: pkg/codegen/templates/routes.go.tmpl
//  2. Run 'make dev' to regenerate
//  3. Do NOT edit this file directly - changes will be lost
//
// This file registers routes for all resource types:
//   - /campaigns (Campaign operations)
//   - /nodes (Node operations)
//   - /nodesets (NodeSet operations)
//   - /profilebindings (ProfileBinding operations)
//
// Route patterns:
//   - GET    /resource              -> List all resources
//   - GET    /resource/{uid}        -> Get specific resource
//   - POST   /resource              -> Create new resource
//   - PUT    /resource/{uid}        -> Update resource spec
//   - PATCH  /resource/{uid}        -> Patch resource spec
//   - DELETE /resource/{uid}        -> Delete resource
//   - PUT    /resource/{uid}/status -> Update resource status
//   - PATCH  /resource/{uid}/status -> Patch resource status
//
// To add middleware to routes:
//  1. Apply middleware in cmd/server/main.go before calling RegisterGeneratedRoutes
//  2. Use r.Use() calls in main.go, not in generated route functions
//
// To add custom routes:
//  1. Create a separate RegisterCustomRoutes function
//  2. Call it after RegisterGeneratedRoutes in main.go
package main

import (
	"github.com/go-chi/chi/v5"
	"github.com/openchami/fabrica/pkg/resource"
)

// registerResourcePrefixes registers UID prefixes for all resource types
// This must be called before any resource creation operations
func registerResourcePrefixes() error {

	resource.RegisterResourcePrefix("Campaign", "campaign")

	resource.RegisterResourcePrefix("Node", "node")

	resource.RegisterResourcePrefix("NodeSet", "nodeset")

	resource.RegisterResourcePrefix("ProfileBinding", "profilebinding")

	return nil
}

// RegisterGeneratedRoutes registers all generated routes
// Note: Middleware should be applied in main.go before calling this function
func RegisterGeneratedRoutes(r chi.Router) {

	// Campaign routes
	r.Route("/campaigns", func(r chi.Router) {
		r.Get("/", GetCampaigns)
		r.Post("/", CreateCampaign)
		r.Route("/{uid}", func(r chi.Router) {
			r.Get("/", GetCampaign)
			r.Put("/", UpdateCampaign)
			r.Patch("/", PatchCampaign)
			r.Delete("/", DeleteCampaign)

			// Status subresource
			r.Route("/status", func(r chi.Router) {
				r.Put("/", UpdateCampaignStatus)
				r.Patch("/", PatchCampaignStatus)
			})
		})
	})

	// Node routes
	r.Route("/nodes", func(r chi.Router) {
		r.Get("/", GetNodes)
		r.Post("/", CreateNode)
		r.Route("/{uid}", func(r chi.Router) {
			r.Get("/", GetNode)
			r.Put("/", UpdateNode)
			r.Patch("/", PatchNode)
			r.Delete("/", DeleteNode)

			// Status subresource
			r.Route("/status", func(r chi.Router) {
				r.Put("/", UpdateNodeStatus)
				r.Patch("/", PatchNodeStatus)
			})
		})
	})

	// NodeSet routes
	r.Route("/nodesets", func(r chi.Router) {
		r.Get("/", GetNodeSets)
		r.Post("/", CreateNodeSet)
		r.Route("/{uid}", func(r chi.Router) {
			r.Get("/", GetNodeSet)
			r.Put("/", UpdateNodeSet)
			r.Patch("/", PatchNodeSet)
			r.Delete("/", DeleteNodeSet)

			// Status subresource
			r.Route("/status", func(r chi.Router) {
				r.Put("/", UpdateNodeSetStatus)
				r.Patch("/", PatchNodeSetStatus)
			})
		})
	})

	// ProfileBinding routes
	r.Route("/profilebindings", func(r chi.Router) {
		r.Get("/", GetProfileBindings)
		r.Post("/", CreateProfileBinding)
		r.Route("/{uid}", func(r chi.Router) {
			r.Get("/", GetProfileBinding)
			r.Put("/", UpdateProfileBinding)
			r.Patch("/", PatchProfileBinding)
			r.Delete("/", DeleteProfileBinding)

			// Status subresource
			r.Route("/status", func(r chi.Router) {
				r.Put("/", UpdateProfileBindingStatus)
				r.Patch("/", PatchProfileBindingStatus)
			})
		})
	})

	// OpenAPI documentation routes
	r.Get("/openapi.json", ServeOpenAPISpec)
	r.Get("/docs", ServeSwaggerUI)
}
