// Code generated by codegen. DO NOT EDIT.
// Copyright © 2025 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT
//
// This file provides a Cobra-based CLI for the node_service API.
// Generated from: pkg/codegen/templates/client-cmd.go.tmpl
//
// To modify the CLI:
//  1. Edit the template file: pkg/codegen/templates/client-cmd.go.tmpl
//  2. Run 'make generate-client-cmd' to regenerate
//  3. Do NOT edit this file directly - changes will be lost
//
// Generated commands for each resource:
//   - client node [list|get|create|update|patch|delete]
//   - client nodeset [list|get|create|update|patch|delete]
//   - client profilebinding [list|get|create|update|patch|delete]
//
// Global flags (available for all commands):
//
//	--server       Server URL (env: NODE_SERVICE_SERVER)
//	--timeout      Request timeout (env: NODE_SERVICE_TIMEOUT)
//	--output, -o   Output format: table, json, yaml (env: NODE_SERVICE_OUTPUT)
//	--version, -v  API version to request: v1, v2beta1, etc. (env: NODE_SERVICE_VERSION)
//	--config       Config file path (default: ~/.node_service-cli.yaml)
//
// Configuration sources (in order of precedence):
//  1. Command-line flags
//  2. Environment variables (NODE_SERVICE_*)
//  3. Config file (~/.node_service-cli.yaml)
//  4. Default values
//
// Usage examples:
//
//	# List all nodes (default version)
//	client node list
//
//	# List nodes with specific version
//	client node list --version v2beta1
//
//	# Get Node as v1
//	client node get <uid> --version v1
//
//	# Create from JSON file with version
//	cat node.json | client node create --version v2beta1
//
//	# Create from inline JSON
//	client node create --spec '{"name":"node-01","description":"Example Node"}'
//
//	# Use environment variables
//	export NODE_SERVICE_SERVER=https://node_service.example.com
//	export NODE_SERVICE_VERSION=v2beta1
//	client node list
//
// To add custom commands:
//  1. Add command definition in template after resource commands
//  2. Register it in init() function
//
// To change output formatting:
//  1. Modify printOutput function to add new formats
//  2. Update output flag validation
//
// To add authentication:
//  1. Add auth flags (--token, --username, etc.)
//  2. Modify getClient to configure auth in http.Client
//  3. Add auth headers in client package
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/spf13/cobra"
	"github.com/spf13/viper"
	"github.com/user/node-service/pkg/client"
)

var (
	cfgFile    string
	serverURL  string
	timeout    time.Duration
	output     string
	apiVersion string
)

func main() {
	if err := rootCmd.Execute(); err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}
}

var rootCmd = &cobra.Command{
	Use:   filepath.Base(os.Args[0]),
	Short: "node_service CLI",
	Long:  `A command-line interface for managing node_service resources.`,
}

func init() {
	cobra.OnInitialize(initConfig)

	// Global flags
	rootCmd.PersistentFlags().StringVar(&cfgFile, "config", "", "config file (default is $HOME/.node_service-cli.yaml)")
	rootCmd.PersistentFlags().StringVar(&serverURL, "server", "http://localhost:8080", "node_service server URL")
	rootCmd.PersistentFlags().DurationVar(&timeout, "timeout", 30*time.Second, "request timeout")
	rootCmd.PersistentFlags().StringVarP(&output, "output", "o", "table", "output format: table, json, yaml")
	rootCmd.PersistentFlags().StringVarP(&apiVersion, "version", "v", "", "API version to request (e.g., v1, v2beta1)")

	// Bind flags to viper
	viper.BindPFlag("server", rootCmd.PersistentFlags().Lookup("server"))
	viper.BindPFlag("timeout", rootCmd.PersistentFlags().Lookup("timeout"))
	viper.BindPFlag("output", rootCmd.PersistentFlags().Lookup("output"))
	viper.BindPFlag("version", rootCmd.PersistentFlags().Lookup("version"))

	// Environment variable support
	viper.SetEnvPrefix("NODE_SERVICE")
	viper.AutomaticEnv()

	// Add resource commands
	rootCmd.AddCommand(nodeCmd)
	rootCmd.AddCommand(nodesetCmd)
	rootCmd.AddCommand(profilebindingCmd)

}

func initConfig() {
	if cfgFile != "" {
		viper.SetConfigFile(cfgFile)
	} else {
		home, err := os.UserHomeDir()
		if err != nil {
			fmt.Fprintf(os.Stderr, "Warning: %v\n", err)
			return
		}

		viper.AddConfigPath(home)
		viper.SetConfigType("yaml")
		viper.SetConfigName(".node_service-cli")
	}

	if err := viper.ReadInConfig(); err == nil {
		fmt.Fprintln(os.Stderr, "Using config file:", viper.ConfigFileUsed())
	}
}

func getClient() (*client.Client, error) {
	serverURL := viper.GetString("server")
	c, err := client.NewClient(serverURL, nil)
	if err != nil {
		return nil, err
	}

	// Apply version if specified
	version := viper.GetString("version")
	if version != "" {
		c = c.WithVersion(version)
	}

	return c, nil
}

func printOutput(data interface{}) error {
	switch output {
	case "json":
		encoder := json.NewEncoder(os.Stdout)
		encoder.SetIndent("", "  ")
		return encoder.Encode(data)
	case "yaml":
		// TODO: Add YAML support if needed
		return fmt.Errorf("YAML output not yet implemented")
	case "table":
		// Simple table output
		encoder := json.NewEncoder(os.Stdout)
		encoder.SetIndent("", "  ")
		return encoder.Encode(data)
	default:
		return fmt.Errorf("unknown output format: %s", output)
	}
}

// setNestedField sets a field in a nested map using dot notation
// Example: setNestedField(map, "status.health", "OK") sets map["status"]["health"] = "OK"
func setNestedField(target map[string]interface{}, path string, value interface{}) {
	parts := strings.Split(path, ".")
	current := target

	// Navigate to the parent of the target field
	for _, part := range parts[:len(parts)-1] {
		if current[part] == nil {
			current[part] = make(map[string]interface{})
		}
		if nested, ok := current[part].(map[string]interface{}); ok {
			current = nested
		} else {
			// Convert to map if it's not already
			current[part] = make(map[string]interface{})
			current = current[part].(map[string]interface{})
		}
	}

	// Set the final field
	finalField := parts[len(parts)-1]
	if value == nil {
		// For unset operations, we use JSON Merge Patch null semantics
		current[finalField] = nil
	} else if stringValue, ok := value.(string); ok {
		// Try to parse as JSON first, then as string
		var jsonValue interface{}
		if err := json.Unmarshal([]byte(stringValue), &jsonValue); err == nil {
			current[finalField] = jsonValue
		} else {
			current[finalField] = stringValue
		}
	} else {
		current[finalField] = value
	}
}

// Node commands
var nodeCmd = &cobra.Command{
	Use:   "node",
	Short: "Manage nodes",
	Long:  `Create, read, update, patch, and delete nodes.`,
}

var nodeListCmd = &cobra.Command{
	Use:   "list",
	Short: "List all nodes",
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		items, err := c.GetNodes(ctx)
		if err != nil {
			return fmt.Errorf("failed to list nodes: %w", err)
		}

		return printOutput(items)
	},
}

var nodeGetCmd = &cobra.Command{
	Use:   "get [uid]",
	Short: "Get a Node by UID",
	Args:  cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		item, err := c.GetNode(ctx, args[0])
		if err != nil {
			return fmt.Errorf("failed to get Node: %w", err)
		}

		return printOutput(item)
	},
}

var nodeCreateCmd = &cobra.Command{
	Use:   "create",
	Short: "Create a new Node",
	Long: `Create a new Node.

Examples:
  # Create from stdin
  echo '{"xname": "example-name", "role": "example-value", "subrole": "example-value", "labels": {"{"key":"value"}": "value"}}' | client node create

  # Create with --spec flag
  client node create --spec '{"xname": "example-name", "role": "example-value", "subrole": "example-value", "labels": {"{"key":"value"}": "value"}}'

Spec fields:
  xname (string) [required]
  role (string)
  subrole (string)
  labels (map[string]string)
`,
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		// Read request from flags or stdin
		reqJSON, _ := cmd.Flags().GetString("spec")
		var req client.CreateNodeRequest

		if reqJSON == "" {
			// Read from stdin if no spec provided
			decoder := json.NewDecoder(os.Stdin)
			if err := decoder.Decode(&req); err != nil {
				return fmt.Errorf("failed to decode request from stdin: %w", err)
			}
		} else {
			// Parse request from JSON string
			if err := json.Unmarshal([]byte(reqJSON), &req); err != nil {
				return fmt.Errorf("failed to parse request JSON: %w", err)
			}
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		item, err := c.CreateNode(ctx, req)
		if err != nil {
			return fmt.Errorf("failed to create Node: %w", err)
		}

		return printOutput(item)
	},
}

var nodeUpdateCmd = &cobra.Command{
	Use:   "update [uid]",
	Short: "Update an existing Node",
	Long: `Update an existing Node.

Examples:
  # Update from stdin
  echo '{"xname": "example-name", "role": "example-value", "subrole": "example-value", "labels": {"{"key":"value"}": "value"}}' | client node update <uid>

  # Update with --spec flag
  client node update <uid> --spec '{"xname": "example-name", "role": "example-value", "subrole": "example-value", "labels": {"{"key":"value"}": "value"}}'

Spec fields:
  xname (string) [required]
  role (string)
  subrole (string)
  labels (map[string]string)
`,
	Args: cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		// Read request from flags or stdin
		reqJSON, _ := cmd.Flags().GetString("spec")
		var req client.UpdateNodeRequest

		if reqJSON == "" {
			// Read from stdin if no spec provided
			decoder := json.NewDecoder(os.Stdin)
			if err := decoder.Decode(&req); err != nil {
				return fmt.Errorf("failed to decode request from stdin: %w", err)
			}
		} else {
			// Parse request from JSON string
			if err := json.Unmarshal([]byte(reqJSON), &req); err != nil {
				return fmt.Errorf("failed to parse request JSON: %w", err)
			}
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		item, err := c.UpdateNode(ctx, args[0], req)
		if err != nil {
			return fmt.Errorf("failed to update Node: %w", err)
		}

		return printOutput(item)
	},
}

var nodePatchCmd = &cobra.Command{
	Use:   "patch [uid]",
	Short: "Patch a Node",
	Long: `Patch an existing Node spec using various patch formats.

IMPORTANT: Only the spec portion of the resource can be patched.
Metadata (name, labels, annotations) and status are managed by the API.

Examples:
  # JSON Merge Patch (simple merge) - patch spec fields
  client node patch <uid> --spec '{"manufacturer":"Intel","model":"Updated Model"}'

  # Shorthand patch (dot notation - most convenient)
  client node patch <uid> --set manufacturer=Intel --set model="Updated Model" --unset customField

  # JSON Patch (RFC 6902 - most powerful)
  client node patch <uid> --json-patch '[
    {"op":"replace","path":"/manufacturer","value":"Intel"},
    {"op":"add","path":"/properties/newField","value":"newValue"}
  ]'

  # From stdin (JSON Merge Patch format)
  echo '{"manufacturer":"AMD","partNumber":"RYZEN-9000"}' | client node patch <uid>

Patch Formats:
  --spec        JSON Merge Patch (RFC 7386) - simple object merge
  --set/--unset Shorthand patch - dot notation for convenience
  --json-patch  JSON Patch (RFC 6902) - operation-based patches
  stdin         JSON Merge Patch format

Shorthand Operations (spec fields only):
  --set field=value     Set a spec field value (supports dot notation)
  --unset field         Remove a spec field (supports dot notation)
  --add field=value     Add to spec array field (field must end with '.-')
  --remove field=value  Remove from spec array field

Note: All patch operations target the resource spec only.
Attempts to patch metadata or status fields will be ignored.`,
	Args: cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		uid := args[0]

		// Get patch flags
		specPatch, _ := cmd.Flags().GetString("spec")
		jsonPatch, _ := cmd.Flags().GetString("json-patch")
		setPairs, _ := cmd.Flags().GetStringArray("set")
		unsetFields, _ := cmd.Flags().GetStringArray("unset")
		addPairs, _ := cmd.Flags().GetStringArray("add")
		removePairs, _ := cmd.Flags().GetStringArray("remove")

		var patchData []byte
		var contentType string

		// Determine patch format and build patch data
		if jsonPatch != "" {
			// JSON Patch (RFC 6902)
			patchData = []byte(jsonPatch)
			contentType = "application/json-patch+json"
		} else if len(setPairs) > 0 || len(unsetFields) > 0 || len(addPairs) > 0 || len(removePairs) > 0 {
			// Shorthand patch - convert to JSON Merge Patch
			patch := make(map[string]interface{})

			// Process --set flags
			for _, setPair := range setPairs {
				parts := strings.SplitN(setPair, "=", 2)
				if len(parts) != 2 {
					return fmt.Errorf("invalid --set format: %s (expected field=value)", setPair)
				}
				setNestedField(patch, parts[0], parts[1])
			}

			// Process --unset flags
			for _, field := range unsetFields {
				setNestedField(patch, field, nil)
			}

			// Process --add flags (add to arrays)
			for _, addPair := range addPairs {
				parts := strings.SplitN(addPair, "=", 2)
				if len(parts) != 2 {
					return fmt.Errorf("invalid --add format: %s (expected field=value)", addPair)
				}
				// For arrays, we'll use JSON Merge Patch append syntax if possible
				// Otherwise convert to JSON Patch
				setNestedField(patch, parts[0], parts[1])
			}

			// Process --remove flags
			for _, removePair := range removePairs {
				parts := strings.SplitN(removePair, "=", 2)
				if len(parts) != 2 {
					return fmt.Errorf("invalid --remove format: %s (expected field=value)", removePair)
				}
				// Remove operations are complex and might need JSON Patch
				// For now, we'll handle simple cases
				return fmt.Errorf("--remove operations require --json-patch format")
			}

			patchBytes, err := json.Marshal(patch)
			if err != nil {
				return fmt.Errorf("failed to marshal shorthand patch: %w", err)
			}
			patchData = patchBytes
			contentType = "application/merge-patch+json"
		} else if specPatch != "" {
			// JSON Merge Patch from --spec
			patchData = []byte(specPatch)
			contentType = "application/merge-patch+json"
		} else {
			// Read from stdin (default to JSON Merge Patch)
			decoder := json.NewDecoder(os.Stdin)
			var patch interface{}
			if err := decoder.Decode(&patch); err != nil {
				return fmt.Errorf("failed to decode patch from stdin: %w", err)
			}
			patchBytes, err := json.Marshal(patch)
			if err != nil {
				return fmt.Errorf("failed to marshal patch: %w", err)
			}
			patchData = patchBytes
			contentType = "application/merge-patch+json"
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		item, err := c.PatchNode(ctx, uid, patchData, contentType)
		if err != nil {
			return fmt.Errorf("failed to patch Node: %w", err)
		}

		return printOutput(item)
	},
}

var nodeDeleteCmd = &cobra.Command{
	Use:   "delete [uid]",
	Short: "Delete a Node",
	Args:  cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		if err := c.DeleteNode(ctx, args[0]); err != nil {
			return fmt.Errorf("failed to delete Node: %w", err)
		}

		fmt.Printf("Node %s deleted successfully\n", args[0])
		return nil
	},
}

func init() {
	nodeCmd.AddCommand(nodeListCmd)
	nodeCmd.AddCommand(nodeGetCmd)
	nodeCmd.AddCommand(nodeCreateCmd)
	nodeCmd.AddCommand(nodeUpdateCmd)
	nodeCmd.AddCommand(nodePatchCmd)
	nodeCmd.AddCommand(nodeDeleteCmd)

	// Add spec flag for create and update commands
	nodeCreateCmd.Flags().String("spec", "", "Node specification in JSON format")
	nodeUpdateCmd.Flags().String("spec", "", "Node specification in JSON format")

	// Add patch command flags
	nodePatchCmd.Flags().String("spec", "", "JSON Merge Patch specification")
	nodePatchCmd.Flags().String("json-patch", "", "JSON Patch operations (RFC 6902)")
	nodePatchCmd.Flags().StringArray("set", nil, "Set field value using dot notation (field=value)")
	nodePatchCmd.Flags().StringArray("unset", nil, "Unset field using dot notation")
	nodePatchCmd.Flags().StringArray("add", nil, "Add value to array field (field=value)")
	nodePatchCmd.Flags().StringArray("remove", nil, "Remove value from array field (field=value)")
}

// NodeSet commands
var nodesetCmd = &cobra.Command{
	Use:   "nodeset",
	Short: "Manage nodesets",
	Long:  `Create, read, update, patch, and delete nodesets.`,
}

var nodesetListCmd = &cobra.Command{
	Use:   "list",
	Short: "List all nodesets",
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		items, err := c.GetNodeSets(ctx)
		if err != nil {
			return fmt.Errorf("failed to list nodesets: %w", err)
		}

		return printOutput(items)
	},
}

var nodesetGetCmd = &cobra.Command{
	Use:   "get [uid]",
	Short: "Get a NodeSet by UID",
	Args:  cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		item, err := c.GetNodeSet(ctx, args[0])
		if err != nil {
			return fmt.Errorf("failed to get NodeSet: %w", err)
		}

		return printOutput(item)
	},
}

var nodesetCreateCmd = &cobra.Command{
	Use:   "create",
	Short: "Create a new NodeSet",
	Long: `Create a new NodeSet.

Examples:
  # Create from stdin
  echo '{"selector": {"{"key":"value"}": "value"}, "xnames": ["["item1","item2"]"], "partitions": ["["item1","item2"]"]}' | client nodeset create

  # Create with --spec flag
  client nodeset create --spec '{"selector": {"{"key":"value"}": "value"}, "xnames": ["["item1","item2"]"], "partitions": ["["item1","item2"]"]}'

Spec fields:
  selector (map[string]string)
  xnames ([]string)
  partitions ([]string)
`,
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		// Read request from flags or stdin
		reqJSON, _ := cmd.Flags().GetString("spec")
		var req client.CreateNodeSetRequest

		if reqJSON == "" {
			// Read from stdin if no spec provided
			decoder := json.NewDecoder(os.Stdin)
			if err := decoder.Decode(&req); err != nil {
				return fmt.Errorf("failed to decode request from stdin: %w", err)
			}
		} else {
			// Parse request from JSON string
			if err := json.Unmarshal([]byte(reqJSON), &req); err != nil {
				return fmt.Errorf("failed to parse request JSON: %w", err)
			}
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		item, err := c.CreateNodeSet(ctx, req)
		if err != nil {
			return fmt.Errorf("failed to create NodeSet: %w", err)
		}

		return printOutput(item)
	},
}

var nodesetUpdateCmd = &cobra.Command{
	Use:   "update [uid]",
	Short: "Update an existing NodeSet",
	Long: `Update an existing NodeSet.

Examples:
  # Update from stdin
  echo '{"selector": {"{"key":"value"}": "value"}, "xnames": ["["item1","item2"]"], "partitions": ["["item1","item2"]"]}' | client nodeset update <uid>

  # Update with --spec flag
  client nodeset update <uid> --spec '{"selector": {"{"key":"value"}": "value"}, "xnames": ["["item1","item2"]"], "partitions": ["["item1","item2"]"]}'

Spec fields:
  selector (map[string]string)
  xnames ([]string)
  partitions ([]string)
`,
	Args: cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		// Read request from flags or stdin
		reqJSON, _ := cmd.Flags().GetString("spec")
		var req client.UpdateNodeSetRequest

		if reqJSON == "" {
			// Read from stdin if no spec provided
			decoder := json.NewDecoder(os.Stdin)
			if err := decoder.Decode(&req); err != nil {
				return fmt.Errorf("failed to decode request from stdin: %w", err)
			}
		} else {
			// Parse request from JSON string
			if err := json.Unmarshal([]byte(reqJSON), &req); err != nil {
				return fmt.Errorf("failed to parse request JSON: %w", err)
			}
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		item, err := c.UpdateNodeSet(ctx, args[0], req)
		if err != nil {
			return fmt.Errorf("failed to update NodeSet: %w", err)
		}

		return printOutput(item)
	},
}

var nodesetPatchCmd = &cobra.Command{
	Use:   "patch [uid]",
	Short: "Patch a NodeSet",
	Long: `Patch an existing NodeSet spec using various patch formats.

IMPORTANT: Only the spec portion of the resource can be patched.
Metadata (name, labels, annotations) and status are managed by the API.

Examples:
  # JSON Merge Patch (simple merge) - patch spec fields
  client nodeset patch <uid> --spec '{"manufacturer":"Intel","model":"Updated Model"}'

  # Shorthand patch (dot notation - most convenient)
  client nodeset patch <uid> --set manufacturer=Intel --set model="Updated Model" --unset customField

  # JSON Patch (RFC 6902 - most powerful)
  client nodeset patch <uid> --json-patch '[
    {"op":"replace","path":"/manufacturer","value":"Intel"},
    {"op":"add","path":"/properties/newField","value":"newValue"}
  ]'

  # From stdin (JSON Merge Patch format)
  echo '{"manufacturer":"AMD","partNumber":"RYZEN-9000"}' | client nodeset patch <uid>

Patch Formats:
  --spec        JSON Merge Patch (RFC 7386) - simple object merge
  --set/--unset Shorthand patch - dot notation for convenience
  --json-patch  JSON Patch (RFC 6902) - operation-based patches
  stdin         JSON Merge Patch format

Shorthand Operations (spec fields only):
  --set field=value     Set a spec field value (supports dot notation)
  --unset field         Remove a spec field (supports dot notation)
  --add field=value     Add to spec array field (field must end with '.-')
  --remove field=value  Remove from spec array field

Note: All patch operations target the resource spec only.
Attempts to patch metadata or status fields will be ignored.`,
	Args: cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		uid := args[0]

		// Get patch flags
		specPatch, _ := cmd.Flags().GetString("spec")
		jsonPatch, _ := cmd.Flags().GetString("json-patch")
		setPairs, _ := cmd.Flags().GetStringArray("set")
		unsetFields, _ := cmd.Flags().GetStringArray("unset")
		addPairs, _ := cmd.Flags().GetStringArray("add")
		removePairs, _ := cmd.Flags().GetStringArray("remove")

		var patchData []byte
		var contentType string

		// Determine patch format and build patch data
		if jsonPatch != "" {
			// JSON Patch (RFC 6902)
			patchData = []byte(jsonPatch)
			contentType = "application/json-patch+json"
		} else if len(setPairs) > 0 || len(unsetFields) > 0 || len(addPairs) > 0 || len(removePairs) > 0 {
			// Shorthand patch - convert to JSON Merge Patch
			patch := make(map[string]interface{})

			// Process --set flags
			for _, setPair := range setPairs {
				parts := strings.SplitN(setPair, "=", 2)
				if len(parts) != 2 {
					return fmt.Errorf("invalid --set format: %s (expected field=value)", setPair)
				}
				setNestedField(patch, parts[0], parts[1])
			}

			// Process --unset flags
			for _, field := range unsetFields {
				setNestedField(patch, field, nil)
			}

			// Process --add flags (add to arrays)
			for _, addPair := range addPairs {
				parts := strings.SplitN(addPair, "=", 2)
				if len(parts) != 2 {
					return fmt.Errorf("invalid --add format: %s (expected field=value)", addPair)
				}
				// For arrays, we'll use JSON Merge Patch append syntax if possible
				// Otherwise convert to JSON Patch
				setNestedField(patch, parts[0], parts[1])
			}

			// Process --remove flags
			for _, removePair := range removePairs {
				parts := strings.SplitN(removePair, "=", 2)
				if len(parts) != 2 {
					return fmt.Errorf("invalid --remove format: %s (expected field=value)", removePair)
				}
				// Remove operations are complex and might need JSON Patch
				// For now, we'll handle simple cases
				return fmt.Errorf("--remove operations require --json-patch format")
			}

			patchBytes, err := json.Marshal(patch)
			if err != nil {
				return fmt.Errorf("failed to marshal shorthand patch: %w", err)
			}
			patchData = patchBytes
			contentType = "application/merge-patch+json"
		} else if specPatch != "" {
			// JSON Merge Patch from --spec
			patchData = []byte(specPatch)
			contentType = "application/merge-patch+json"
		} else {
			// Read from stdin (default to JSON Merge Patch)
			decoder := json.NewDecoder(os.Stdin)
			var patch interface{}
			if err := decoder.Decode(&patch); err != nil {
				return fmt.Errorf("failed to decode patch from stdin: %w", err)
			}
			patchBytes, err := json.Marshal(patch)
			if err != nil {
				return fmt.Errorf("failed to marshal patch: %w", err)
			}
			patchData = patchBytes
			contentType = "application/merge-patch+json"
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		item, err := c.PatchNodeSet(ctx, uid, patchData, contentType)
		if err != nil {
			return fmt.Errorf("failed to patch NodeSet: %w", err)
		}

		return printOutput(item)
	},
}

var nodesetDeleteCmd = &cobra.Command{
	Use:   "delete [uid]",
	Short: "Delete a NodeSet",
	Args:  cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		if err := c.DeleteNodeSet(ctx, args[0]); err != nil {
			return fmt.Errorf("failed to delete NodeSet: %w", err)
		}

		fmt.Printf("NodeSet %s deleted successfully\n", args[0])
		return nil
	},
}

func init() {
	nodesetCmd.AddCommand(nodesetListCmd)
	nodesetCmd.AddCommand(nodesetGetCmd)
	nodesetCmd.AddCommand(nodesetCreateCmd)
	nodesetCmd.AddCommand(nodesetUpdateCmd)
	nodesetCmd.AddCommand(nodesetPatchCmd)
	nodesetCmd.AddCommand(nodesetDeleteCmd)

	// Add spec flag for create and update commands
	nodesetCreateCmd.Flags().String("spec", "", "NodeSet specification in JSON format")
	nodesetUpdateCmd.Flags().String("spec", "", "NodeSet specification in JSON format")

	// Add patch command flags
	nodesetPatchCmd.Flags().String("spec", "", "JSON Merge Patch specification")
	nodesetPatchCmd.Flags().String("json-patch", "", "JSON Patch operations (RFC 6902)")
	nodesetPatchCmd.Flags().StringArray("set", nil, "Set field value using dot notation (field=value)")
	nodesetPatchCmd.Flags().StringArray("unset", nil, "Unset field using dot notation")
	nodesetPatchCmd.Flags().StringArray("add", nil, "Add value to array field (field=value)")
	nodesetPatchCmd.Flags().StringArray("remove", nil, "Remove value from array field (field=value)")
}

// ProfileBinding commands
var profilebindingCmd = &cobra.Command{
	Use:   "profilebinding",
	Short: "Manage profilebindings",
	Long:  `Create, read, update, patch, and delete profilebindings.`,
}

var profilebindingListCmd = &cobra.Command{
	Use:   "list",
	Short: "List all profilebindings",
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		items, err := c.GetProfileBindings(ctx)
		if err != nil {
			return fmt.Errorf("failed to list profilebindings: %w", err)
		}

		return printOutput(items)
	},
}

var profilebindingGetCmd = &cobra.Command{
	Use:   "get [uid]",
	Short: "Get a ProfileBinding by UID",
	Args:  cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		item, err := c.GetProfileBinding(ctx, args[0])
		if err != nil {
			return fmt.Errorf("failed to get ProfileBinding: %w", err)
		}

		return printOutput(item)
	},
}

var profilebindingCreateCmd = &cobra.Command{
	Use:   "create",
	Short: "Create a new ProfileBinding",
	Long: `Create a new ProfileBinding.

Examples:
  # Create from stdin
  echo '{"targetRef": "{}", "profile": "example-value", "bootProfileOverride": "example-value", "configGroupOverrides": ["["item1","item2"]"]}' | client profilebinding create

  # Create with --spec flag
  client profilebinding create --spec '{"targetRef": "{}", "profile": "example-value", "bootProfileOverride": "example-value", "configGroupOverrides": ["["item1","item2"]"]}'

Spec fields:
  targetRef (v1.BindingTarget) [required]
  profile (string) [required]
  bootProfileOverride (string)
  configGroupOverrides ([]string)
`,
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		// Read request from flags or stdin
		reqJSON, _ := cmd.Flags().GetString("spec")
		var req client.CreateProfileBindingRequest

		if reqJSON == "" {
			// Read from stdin if no spec provided
			decoder := json.NewDecoder(os.Stdin)
			if err := decoder.Decode(&req); err != nil {
				return fmt.Errorf("failed to decode request from stdin: %w", err)
			}
		} else {
			// Parse request from JSON string
			if err := json.Unmarshal([]byte(reqJSON), &req); err != nil {
				return fmt.Errorf("failed to parse request JSON: %w", err)
			}
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		item, err := c.CreateProfileBinding(ctx, req)
		if err != nil {
			return fmt.Errorf("failed to create ProfileBinding: %w", err)
		}

		return printOutput(item)
	},
}

var profilebindingUpdateCmd = &cobra.Command{
	Use:   "update [uid]",
	Short: "Update an existing ProfileBinding",
	Long: `Update an existing ProfileBinding.

Examples:
  # Update from stdin
  echo '{"targetRef": "{}", "profile": "example-value", "bootProfileOverride": "example-value", "configGroupOverrides": ["["item1","item2"]"]}' | client profilebinding update <uid>

  # Update with --spec flag
  client profilebinding update <uid> --spec '{"targetRef": "{}", "profile": "example-value", "bootProfileOverride": "example-value", "configGroupOverrides": ["["item1","item2"]"]}'

Spec fields:
  targetRef (v1.BindingTarget) [required]
  profile (string) [required]
  bootProfileOverride (string)
  configGroupOverrides ([]string)
`,
	Args: cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		// Read request from flags or stdin
		reqJSON, _ := cmd.Flags().GetString("spec")
		var req client.UpdateProfileBindingRequest

		if reqJSON == "" {
			// Read from stdin if no spec provided
			decoder := json.NewDecoder(os.Stdin)
			if err := decoder.Decode(&req); err != nil {
				return fmt.Errorf("failed to decode request from stdin: %w", err)
			}
		} else {
			// Parse request from JSON string
			if err := json.Unmarshal([]byte(reqJSON), &req); err != nil {
				return fmt.Errorf("failed to parse request JSON: %w", err)
			}
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		item, err := c.UpdateProfileBinding(ctx, args[0], req)
		if err != nil {
			return fmt.Errorf("failed to update ProfileBinding: %w", err)
		}

		return printOutput(item)
	},
}

var profilebindingPatchCmd = &cobra.Command{
	Use:   "patch [uid]",
	Short: "Patch a ProfileBinding",
	Long: `Patch an existing ProfileBinding spec using various patch formats.

IMPORTANT: Only the spec portion of the resource can be patched.
Metadata (name, labels, annotations) and status are managed by the API.

Examples:
  # JSON Merge Patch (simple merge) - patch spec fields
  client profilebinding patch <uid> --spec '{"manufacturer":"Intel","model":"Updated Model"}'

  # Shorthand patch (dot notation - most convenient)
  client profilebinding patch <uid> --set manufacturer=Intel --set model="Updated Model" --unset customField

  # JSON Patch (RFC 6902 - most powerful)
  client profilebinding patch <uid> --json-patch '[
    {"op":"replace","path":"/manufacturer","value":"Intel"},
    {"op":"add","path":"/properties/newField","value":"newValue"}
  ]'

  # From stdin (JSON Merge Patch format)
  echo '{"manufacturer":"AMD","partNumber":"RYZEN-9000"}' | client profilebinding patch <uid>

Patch Formats:
  --spec        JSON Merge Patch (RFC 7386) - simple object merge
  --set/--unset Shorthand patch - dot notation for convenience
  --json-patch  JSON Patch (RFC 6902) - operation-based patches
  stdin         JSON Merge Patch format

Shorthand Operations (spec fields only):
  --set field=value     Set a spec field value (supports dot notation)
  --unset field         Remove a spec field (supports dot notation)
  --add field=value     Add to spec array field (field must end with '.-')
  --remove field=value  Remove from spec array field

Note: All patch operations target the resource spec only.
Attempts to patch metadata or status fields will be ignored.`,
	Args: cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		uid := args[0]

		// Get patch flags
		specPatch, _ := cmd.Flags().GetString("spec")
		jsonPatch, _ := cmd.Flags().GetString("json-patch")
		setPairs, _ := cmd.Flags().GetStringArray("set")
		unsetFields, _ := cmd.Flags().GetStringArray("unset")
		addPairs, _ := cmd.Flags().GetStringArray("add")
		removePairs, _ := cmd.Flags().GetStringArray("remove")

		var patchData []byte
		var contentType string

		// Determine patch format and build patch data
		if jsonPatch != "" {
			// JSON Patch (RFC 6902)
			patchData = []byte(jsonPatch)
			contentType = "application/json-patch+json"
		} else if len(setPairs) > 0 || len(unsetFields) > 0 || len(addPairs) > 0 || len(removePairs) > 0 {
			// Shorthand patch - convert to JSON Merge Patch
			patch := make(map[string]interface{})

			// Process --set flags
			for _, setPair := range setPairs {
				parts := strings.SplitN(setPair, "=", 2)
				if len(parts) != 2 {
					return fmt.Errorf("invalid --set format: %s (expected field=value)", setPair)
				}
				setNestedField(patch, parts[0], parts[1])
			}

			// Process --unset flags
			for _, field := range unsetFields {
				setNestedField(patch, field, nil)
			}

			// Process --add flags (add to arrays)
			for _, addPair := range addPairs {
				parts := strings.SplitN(addPair, "=", 2)
				if len(parts) != 2 {
					return fmt.Errorf("invalid --add format: %s (expected field=value)", addPair)
				}
				// For arrays, we'll use JSON Merge Patch append syntax if possible
				// Otherwise convert to JSON Patch
				setNestedField(patch, parts[0], parts[1])
			}

			// Process --remove flags
			for _, removePair := range removePairs {
				parts := strings.SplitN(removePair, "=", 2)
				if len(parts) != 2 {
					return fmt.Errorf("invalid --remove format: %s (expected field=value)", removePair)
				}
				// Remove operations are complex and might need JSON Patch
				// For now, we'll handle simple cases
				return fmt.Errorf("--remove operations require --json-patch format")
			}

			patchBytes, err := json.Marshal(patch)
			if err != nil {
				return fmt.Errorf("failed to marshal shorthand patch: %w", err)
			}
			patchData = patchBytes
			contentType = "application/merge-patch+json"
		} else if specPatch != "" {
			// JSON Merge Patch from --spec
			patchData = []byte(specPatch)
			contentType = "application/merge-patch+json"
		} else {
			// Read from stdin (default to JSON Merge Patch)
			decoder := json.NewDecoder(os.Stdin)
			var patch interface{}
			if err := decoder.Decode(&patch); err != nil {
				return fmt.Errorf("failed to decode patch from stdin: %w", err)
			}
			patchBytes, err := json.Marshal(patch)
			if err != nil {
				return fmt.Errorf("failed to marshal patch: %w", err)
			}
			patchData = patchBytes
			contentType = "application/merge-patch+json"
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		item, err := c.PatchProfileBinding(ctx, uid, patchData, contentType)
		if err != nil {
			return fmt.Errorf("failed to patch ProfileBinding: %w", err)
		}

		return printOutput(item)
	},
}

var profilebindingDeleteCmd = &cobra.Command{
	Use:   "delete [uid]",
	Short: "Delete a ProfileBinding",
	Args:  cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		c, err := getClient()
		if err != nil {
			return fmt.Errorf("failed to create client: %w", err)
		}

		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		defer cancel()

		if err := c.DeleteProfileBinding(ctx, args[0]); err != nil {
			return fmt.Errorf("failed to delete ProfileBinding: %w", err)
		}

		fmt.Printf("ProfileBinding %s deleted successfully\n", args[0])
		return nil
	},
}

func init() {
	profilebindingCmd.AddCommand(profilebindingListCmd)
	profilebindingCmd.AddCommand(profilebindingGetCmd)
	profilebindingCmd.AddCommand(profilebindingCreateCmd)
	profilebindingCmd.AddCommand(profilebindingUpdateCmd)
	profilebindingCmd.AddCommand(profilebindingPatchCmd)
	profilebindingCmd.AddCommand(profilebindingDeleteCmd)

	// Add spec flag for create and update commands
	profilebindingCreateCmd.Flags().String("spec", "", "ProfileBinding specification in JSON format")
	profilebindingUpdateCmd.Flags().String("spec", "", "ProfileBinding specification in JSON format")

	// Add patch command flags
	profilebindingPatchCmd.Flags().String("spec", "", "JSON Merge Patch specification")
	profilebindingPatchCmd.Flags().String("json-patch", "", "JSON Patch operations (RFC 6902)")
	profilebindingPatchCmd.Flags().StringArray("set", nil, "Set field value using dot notation (field=value)")
	profilebindingPatchCmd.Flags().StringArray("unset", nil, "Unset field using dot notation")
	profilebindingPatchCmd.Flags().StringArray("add", nil, "Add value to array field (field=value)")
	profilebindingPatchCmd.Flags().StringArray("remove", nil, "Remove value from array field (field=value)")
}
